### ISSUE TITLE
Fix memory leaks

### ISSUE THREAD

**Issue by chges100** [hhuOS/hhuOS#15]
hhuOS seams to have some small memory leaks that appear frequently.
They have to be detected and fixed.

**Comment by chges100** [comment]
Fixed memory leak in 4f802f2a5beae1e5872360d36cb120c9dd13acc2

**Comment by chges100** [comment]
Fixed 4K memory leak by adding destructor be90d307dd236f82b3bb6d251dbaa9db9a04174b

**Comment by fruhland** [comment]
There are currently no apparent memory leaks in the kernel. This issue may be reopened, once new leaks occur.
