### ISSUE TITLE
No mouse movements in Mouse-App

### ISSUE THREAD

**Issue by chges100** [hhuOS/hhuOS#3]
The small white box in the Mouse-App, representing the cursor, does not move when the mouse is operated. This problem occurs in QEMU with Touchpad and USB-Mouse. 
Not tested on real hardware.

**Comment by faruh100** [comment]
There was an error in the EventBus, which prevented the App from receiving MouseEvents.
This has been fixed @filkra.

**Comment by faruh100** [comment]
After some time, the mouse just randomly stops working. This could be related to #11. Maybe it would help to register the mouse as an `IODevice`.

**Comment by faruh100** [comment]
Fixed with 8a0bd96ef6eed2c2ac2f21d461ce6f850d41a972.
