### ISSUE TITLE
Parse Symbol files

### ISSUE THREAD

**Issue by chges100** [hhuOS/hhuOS#30]
Parse symbol files during booting in order to show function names in Bluescreen. This function has to be rewritten from scratch since the old version is not longer compatible.

**Comment by fruhland** [comment]
Stack traces including function names are now shown for the kernel and user space applications. Involved commits:
- 61675ea7ab908e279a11a209f9090b6ae61beb9d
- 53a01ef1b1ab42b319af45c1d6a7248764811485
- 0520b51890e1ee4e4b7d30289268c75440c8bc44
- 1ca73d2ee31a5281220ee65afc8f824e391b98d4
- de3a06696f3dad80a74d281400b4657df569db84
- 22785d1e6449c9315b2971060fbd2f765bc4190d
