### ISSUE TITLE
Proper attribution for assets

### ISSUE THREAD

**Issue by 99991** [hhuOS/hhuOS#36]
Some assets listed [in the README](https://github.com/hhuOS/hhuOS#notes) are licensed under the [Creative Commons Attribution v4.0 International license](https://creativecommons.org/licenses/by/4.0/legalcode).

I believe there is still an opportunity to adhere more closely to the license text, such as by including a link to the license. See the Attribution section of the license for more information.

For the Retro Cloud Tileset, I could not find any reference to a license which would allow redistribution. Did I miss something?

**Comment by fruhland** [comment]
Thanks for your concern,
we updated the README file and got permission to use Retro Cloud Tileset directly from the author himself (See comments on itch.io).
