### ISSUE TITLE
System does not start on AMD Phenom

### ISSUE THREAD

**Issue by chges100** [hhuOS/hhuOS#4]
The system has boot problems on AMD systems, confirmed on AMD Phenom II. It hangs on startup in main-method. Maybe a timing problem, because some manually inserted printf-outputs change the behaviour.

Note: Emulating AMD Phenom in QEMU does not show this behaviour - so this is not helpful for debugging reasons.

**Comment by chges100** [comment]
With some outputs via puts right after `pit.plugin` in `main` the system boots.

Maybe the problem is related to [https://github.com/hhuOS/hhuOS/issues/6](url)

**Comment by faruh100** [comment]
There seemed to be some kind of timing problem, regarding the PIT initialization. However, it does not occur anymore after the latest commits, which included some heavy refactoring of the PIT- and TimeService-classes, as well as the whole boot process.
I tested the OS on a Phenom II X6 1100T and an Athlon II X2 215 and it wirked flawlessy on both machines.
